### ISSUE TITLE
How do I use this

### ISSUE THREAD

**Issue by fudogz** [mapbox/mapbox-studio-winter-wonderland.tm2#2]
So I created an account on mapbox and used mapbox studio. It is not clear how to use these files after downloading. In fact there are no instruction at all. I've even tried installing the classic version of MapBox to see if I can somehow use these downloaded files - nope, not a chance.

So how is someone meant to use these files?

**Comment by dasulit** [comment]
As this style is not compatible with the current Mapbox Studio, we're archiving this repo.
